export const REELS_MOCK = [
        {
            id: 1,
            username: "arch_visuals",
            profilePic: "https://randomuser.me/api/portraits/men/32.jpg",
            videoUrl: "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
            caption: "Midnight in the concrete jungle. #Architecture #CityNights",
            audioName: "arch_visuals • Original Audio",
            likes: "12.5K",
            comments: "450",
            isLiked: false,
            isSaved: true
        },
        {
            id: 2,
            username: "minimal_design",
            profilePic: "https://randomuser.me/api/portraits/women/44.jpg",
            videoUrl: "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
            caption: "The beauty of shadows and light.",
            audioName: "Lofi Beats for Designing",
            likes: "8,902",
            comments: "128",
            isLiked: true,
            isSaved: false
        },
        {
            id: 3,
            username: "skyline_drones",
            profilePic: "https://randomuser.me/api/portraits/men/85.jpg",
            videoUrl: "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
            caption: "Golden hour from above. 🚁 #Skyline",
            audioName: "skyline_drones • Original Audio",
            likes: "45.2K",
            comments: "1,032",
            isLiked: false,
            isSaved: true
        },
        {
            id: 4,
            username: "brutalist_guy",
            profilePic: "https://randomuser.me/api/portraits/men/41.jpg",
            videoUrl: "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
            caption: "Geometric perfection in raw concrete.",
            audioName: "Techno Ambient - Deep House",
            likes: "3,400",
            comments: "95",
            isLiked: false,
            isSaved: false
        },
        {
            id: 5,
            username: "urban_explore",
            profilePic: "https://randomuser.me/api/portraits/women/12.jpg",
            videoUrl: "https://storage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
            caption: "POV: You found the secret entrance. 🔦",
            audioName: "urban_explore • Original Audio",
            likes: "102K",
            comments: "3,410",
            isLiked: true,
            isSaved: true
        },
        {
            id: 6,
            username: "interior_eye",
            profilePic: "https://randomuser.me/api/portraits/women/25.jpg",
            videoUrl: "https://storage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
            caption: "Welcome to the dream loft project.",
            audioName: "Aesthetic Morning - Chill",
            likes: "25.1K",
            comments: "560",
            isLiked: false,
            isSaved: false
        },
        {
            id: 7,
            username: "green_structures",
            profilePic: "https://randomuser.me/api/portraits/women/68.jpg",
            videoUrl: "https://storage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
            caption: "Vertical forests are the future. 🌿",
            audioName: "Nature Sounds - Relaxation",
            likes: "67.8K",
            comments: "890",
            isLiked: true,
            isSaved: true
        },
        {
            id: 8,
            username: "neon_metropolis",
            profilePic: "https://randomuser.me/api/portraits/women/90.jpg",
            videoUrl: "https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
            caption: "Lost in the Tokyo lights.",
            audioName: "Synthwave Nights - 1984",
            likes: "15.4K",
            comments: "210",
            isLiked: false,
            isSaved: false
        },
        {
            id: 9,
            username: "blueprint_king",
            profilePic: "https://randomuser.me/api/portraits/men/20.jpg",
            videoUrl: "https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
            caption: "From paper to reality. The process. ✍️",
            audioName: "blueprint_king • Original Audio",
            likes: "2,300",
            comments: "45",
            isLiked: false,
            isSaved: true
        },
        {
            id: 10,
            username: "facade_fix",
            profilePic: "https://randomuser.me/api/portraits/men/1.jpg",
            videoUrl: "https://storage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
            caption: "The sky belongs to the glass.",
            audioName: "facade_fix • Original Audio",
            likes: "12.1K",
            comments: "156",
            isLiked: false,
            isSaved: false
        }, {
            id: 11,
            username: "concrete_poetry",
            profilePic: "https://randomuser.me/api/portraits/men/46.jpg",
            videoUrl: "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
            caption: "The texture of brutalism. #Concrete #Design",
            audioName: "Industrial Ambient",
            likes: "4.2K",
            comments: "89",
            isLiked: false,
            isSaved: false
        },
        {
            id: 12,
            username: "glass_house",
            profilePic: "https://randomuser.me/api/portraits/women/33.jpg",
            videoUrl: "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
            caption: "Living in a transparent world.",
            audioName: "glass_house • Original Audio",
            likes: "18.9K",
            comments: "245",
            isLiked: true,
            isSaved: true
        },
        {
            id: 13,
            username: "urban_sketches",
            profilePic: "https://randomuser.me/api/portraits/men/12.jpg",
            videoUrl: "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
            caption: "Speed sketching the skyline.",
            audioName: "Lo-fi Hip Hop Radio",
            likes: "2,100",
            comments: "34",
            isLiked: false,
            isSaved: false
        },
        {
            id: 14,
            username: "timber_frame",
            profilePic: "https://randomuser.me/api/portraits/women/22.jpg",
            videoUrl: "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
            caption: "Sustainable wood structures. 🌲",
            audioName: "Forest Sounds",
            likes: "11.2K",
            comments: "156",
            isLiked: false,
            isSaved: true
        },
        {
            id: 15,
            username: "metro_modern",
            profilePic: "https://randomuser.me/api/portraits/men/55.jpg",
            videoUrl: "https://storage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
            caption: "The geometry of the subway station.",
            audioName: "metro_modern • Original Audio",
            likes: "9,400",
            comments: "112",
            isLiked: true,
            isSaved: false
        }
    ];